# Generated by Django 4.2 on 2023-04-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_films',
            new_name='TEST_Like_films',
        ),
    ]
