# Generated by Django 4.2 on 2023-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_cinemas_films_films_cost_like_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='description',
        ),
        migrations.AddField(
            model_name='films',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
