# Generated by Django 4.2 on 2023-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_films_description_films_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
