# Generated by Django 4.2 on 2023-05-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_films_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='name',
            new_name='film_name',
        ),
        migrations.RenameField(
            model_name='films_cost',
            old_name='purchase',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='films_cost',
            name='rental',
        ),
        migrations.AddField(
            model_name='films_cost',
            name='quality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='films_cost',
            name='viewing_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
