# Generated by Django 4.2 on 2023-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_name_films_film_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemas',
            name='id_cinema',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='films',
            name='id_film',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
