# Generated by Django 4.2 on 2023-05-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_cinemas_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemas',
            name='year',
        ),
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
