# Generated by Django 4.2 on 2023-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_remove_cinemas_year_films_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='link',
        ),
    ]
