# Generated by Django 4.2 on 2023-06-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_remove_films_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films_cost',
            name='id_cinema',
        ),
    ]
