# Generated by Django 4.2 on 2023-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_remove_like_films_id_user_like_films_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films_cost',
            name='id_filmRequest',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
