# Generated by Django 4.2 on 2023-06-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_alter_films_cost_id_filmrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='id_film',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
