# Generated by Django 4.2 on 2023-06-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_films_id_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='id_film',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
