# Generated by Django 4.2 on 2023-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_alter_films_id_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_films',
            name='id',
        ),
        migrations.AddField(
            model_name='like_films',
            name='id_like_film',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='films_cost',
            name='cost',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
