# Generated by Django 4.2 on 2023-06-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_remove_like_films_id_like_films_id_like_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films_cost',
            name='id_filmRequest',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
