# Generated by Django 4.2 on 2023-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_alter_films_id_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='films_cost',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
