# Generated by Django 4.2 on 2023-06-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_films_cost_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='id_film',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
