# Generated by Django 4.2 on 2023-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_alter_films_id_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_films',
            name='id_like_film',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
